### PR TITLE
Seconds indicator moves every second

### PR DESCRIPTION
**Pull request by dcormier**
Changed seconds indicator to move every second, rather than only every 15 seconds.

### CODE REVIEW

**Comment by C-D-Lewis** [comment]
Any change in the core functionality will need to be exposed as an option in the HTML config file. The default behavior is also more power friendly.

**Comment by dcormier** [comment]
Sure thing. Would you like to add it as a sub-option to the current "Animations" option that already dictates whether the seconds are shown at all (among other things)?

**Comment by C-D-Lewis** [comment]
Sounds like a good idea. It should only take effect if both booleans are set to `true` on the C side.

**Comment by dcormier** [comment]
OK, that's the direction I'll take. I'll ping you when I've updated this pull request.

**Comment by dcormier** [comment]
Alright @C-D-Lewis, see how that suits you.

**Comment by C-D-Lewis** [comment]
Looks good to me. Have you verified that it works on all platforms?

**Comment by dcormier** [comment]
Yup.

**Comment by dcormier** [comment]
RIP

**Pull request closed without merging**
